import 'package:aura_svn/app_theme.dart';
import 'package:aura_svn/language_scope.dart';
import 'package:flutter/material.dart';

class RevisionText extends StatelessWidget {
  const RevisionText({super.key, required this.revision});

  final int revision;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return Text(
      revision.toString(),
      style: theme.textTheme.titleSmall?.copyWith(
        color: theme.colorScheme.primary,
        fontWeight: FontWeight.w600,
      ),
    );
  }
}

class MiniMetaChip extends StatelessWidget {
  const MiniMetaChip({
    super.key,
    required this.icon,
    required this.label,
  });

  final IconData icon;
  final String label;

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
      decoration: BoxDecoration(
        color: aura(context).surfaceSoft,
        borderRadius: BorderRadius.circular(999),
        border: Border.all(color: aura(context).border),
      ),
      child: Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          Icon(icon, size: 14, color: aura(context).textMuted),
          const SizedBox(width: 4),
          Text(
            label,
            style: Theme.of(context).textTheme.labelSmall?.copyWith(
                  color: aura(context).textMuted,
                  fontWeight: FontWeight.w600,
                ),
          ),
        ],
      ),
    );
  }
}

class InfoLine extends StatelessWidget {
  const InfoLine({super.key, required this.label, required this.value});

  final String label;
  final String value;

  @override
  Widget build(BuildContext context) {
    return Row(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        SizedBox(
          width: 86,
          child: Text(
            label,
            style: Theme.of(context).textTheme.labelSmall?.copyWith(
                  color: aura(context).textSubtle,
                  fontWeight: FontWeight.w600,
                ),
          ),
        ),
        Expanded(
          child: SelectableText(
            value,
            style: const TextStyle(fontSize: 12.5),
          ),
        ),
      ],
    );
  }
}

class SmallChip extends StatelessWidget {
  const SmallChip({super.key, required this.label, required this.value});

  final String label;
  final String value;

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 6),
      decoration: BoxDecoration(
        color: aura(context).surfaceAlt,
        borderRadius: BorderRadius.circular(999),
        border: Border.all(color: aura(context).border),
      ),
      child: Text(
        '$label: $value',
        style: const TextStyle(fontSize: 12, fontWeight: FontWeight.w600),
      ),
    );
  }
}

class EmptyDataCard extends StatelessWidget {
  const EmptyDataCard({super.key});

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final panelBg = theme.brightness == Brightness.dark
        ? cyberBase
        : aura(context).surfaceAlt;

    return Material(
      color: panelBg,
      child: Center(
        child: Padding(
          padding: const EdgeInsets.all(32),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Icon(
                Icons.cloud_download_outlined,
                size: 64,
                color: theme.colorScheme.primary,
              ),
              const SizedBox(height: 18),
              Text(
                t(context, '尚無輸出資料', 'No Output Data'),
                style: theme.textTheme.titleLarge?.copyWith(
                  fontWeight: FontWeight.w600,
                ),
              ),
              const SizedBox(height: 8),
              Text(
                t(
                  context,
                  '選擇 SVN 庫後按下「執行增量更新」，UI 會讀取 loader 產生的 JSON 與 CSV 分片。',
                  'Select an SVN repository and run an incremental update. The UI will load the JSON and CSV shards generated by the loader.',
                ),
                textAlign: TextAlign.center,
              ),
            ],
          ),
        ),
      ),
    );
  }
}
